source 'http://rubygems.org'

gem 'thin', '>= 1.4.1'
gem 'dm-postgres-adapter', '>= 1.2.0'
gem 'rubygems-bundler', '>= 1.0.2'
gem 'sinatra', '>= 1.3.2'
gem 'data_mapper', '>= 1.2.0'
gem 'dm-timestamps', '>= 1.2.0'
gem 'rack-flash3', '>= 1.0.1'
gem 'sinatra-redirect-with-flash', '>= 0.2.0'
gem 'pg'
